# This workflow will build and test a golang project for multiple versions of Go
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.18", "1.19", "1.20", "1.21", ">=1.22"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Build Go ${{ matrix.go }}
        run: go version && go build -v ./...

      - name: Test Go ${{ matrix.go }}
        run: go version && go test -v ./...
